### ISSUE TITLE
node-bass fails to install on OSX 10.13.3

### ISSUE THREAD

**Issue by daniyel** [auth0/node-baas#38]
Hi.

I am trying to install node-baas locally on my MacBook Pro and I get an error. Node version is `v10.6.0` and npm version is `6.4.0`.

```
me@Mes-MacBook-Pro: ~/Workspace/infrastructure/baas-client$ npm i auth0/node-baas
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

> v8-profiler-node8@5.7.8 preinstall /Users/me/Workspace/infrastructure/baas-client/node_modules/v8-profiler-node8
> node -e 'process.exit(0)'


> dtrace-provider@0.8.7 install /Users/me/Workspace/infrastructure/baas-client/node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js

  ACTION binding_gyp_ndtp_target_build_ndtp .
  TOUCH Release/obj.target/ndtp.stamp

> gc-stats@1.0.2 install /Users/me/Workspace/infrastructure/baas-client/node_modules/gc-stats
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://node-binaries.s3.amazonaws.com/gcstats/v1.0.2/Release/node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for gc-stats@1.0.2 and node@10.6.0 (node-v64 ABI) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://node-binaries.s3.amazonaws.com/gcstats/v1.0.2/Release/node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for gc-stats@1.0.2 and node@10.6.0 (node-v64 ABI) (falling back to source compile with node-gyp)
  CXX(target) Release/obj.target/gcstats/src/gcstats.o
  CXX(target) Release/obj.target/gcstats/src/gcstats.o
../src/gcstats.cc:132:19: warning: 'Call' is deprecated [-Wdeprecated-declarations]
        afterGCCallback->Call(1, arguments);
                         ^
../../nan/nan.h:1646:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:102:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/gcstats.cc:132:19: warning: 'Call' is deprecated [-Wdeprecated-declarations]
        afterGCCallback->Call(1, arguments);
                         ^
../../nan/nan.h:1646:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:102:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
1 warning generated.
1 warning generated.
rm: ./Release/.deps/Release/obj.target/gcstats/src/gcstats.o.d.raw: No such file or directory
make: *** [Release/obj.target/gcstats/src/gcstats.o] Error 1
gyp ERR! build error
  SOLINK_MODULE(target) Release/gcstats.node
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.4.0
gyp ERR! command "/usr/local/Cellar/node/10.6.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/me/Workspace/infrastructure/baas-client/node_modules/gc-stats/build/gcstats/v1.0.2/Release/node-v64-darwin-x64/gcstats.node" "--module_name=gcstats" "--module_path=/Users/me/Workspace/infrastructure/baas-client/node_modules/gc-stats/build/gcstats/v1.0.2/Release/node-v64-darwin-x64"
gyp ERR! cwd /Users/me/Workspace/infrastructure/baas-client/node_modules/gc-stats
gyp ERR! node -v v10.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/10.6.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/me/Workspace/infrastructure/baas-client/node_modules/gc-stats/build/gcstats/v1.0.2/Release/node-v64-darwin-x64/gcstats.node --module_name=gcstats --module_path=/Users/me/Workspace/infrastructure/baas-client/node_modules/gc-stats/build/gcstats/v1.0.2/Release/node-v64-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/me/Workspace/infrastructure/baas-client/node_modules/gc-stats/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
node-pre-gyp ERR! System Darwin 17.4.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/10.6.0/bin/node" "/Users/me/Workspace/infrastructure/baas-client/node_modules/gc-stats/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/me/Workspace/infrastructure/baas-client/node_modules/gc-stats
node-pre-gyp ERR! node -v v10.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/Cellar/node/10.6.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/me/Workspace/infrastructure/baas-client/node_modules/gc-stats/build/gcstats/v1.0.2/Release/node-v64-darwin-x64/gcstats.node --module_name=gcstats --module_path=/Users/me/Workspace/infrastructure/baas-client/node_modules/gc-stats/build/gcstats/v1.0.2/Release/node-v64-darwin-x64' (1)
  COPY /Users/me/Workspace/infrastructure/baas-client/node_modules/gc-stats/build/gcstats/v1.0.2/Release/node-v64-darwin-x64/gcstats.node
  TOUCH Release/obj.target/action_after_build.stamp
npm WARN enoent ENOENT: no such file or directory, open '/Users/me/Workspace/infrastructure/baas-client/package.json'
npm WARN baas-client No description
npm WARN baas-client No repository field.
npm WARN baas-client No README data
npm WARN baas-client No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gc-stats@1.0.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gc-stats@1.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/me/.npm/_logs/2018-09-04T14_52_39_729Z-debug.log
```

Best regards.

**Comment by daniyel** [comment]
So I just updated node version to `10.9.0` and still no success. I noticed that version used in Dockerfile is `8.11.2`, do I need to downgrade my node version?

```
me@Mes-MacBook-Pro: ~/Workspace/infrastructure/baas-client$ npm i auth0/node-baas

> gc-stats@1.0.2 install /Users/me/Workspace/infrastructure/baas-client/node_modules/gc-stats
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://node-binaries.s3.amazonaws.com/gcstats/v1.0.2/Release/node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for gc-stats@1.0.2 and node@10.9.0 (node-v64 ABI) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://node-binaries.s3.amazonaws.com/gcstats/v1.0.2/Release/node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for gc-stats@1.0.2 and node@10.9.0 (node-v64 ABI) (falling back to source compile with node-gyp)
  CXX(target) Release/obj.target/gcstats/src/gcstats.o
  CXX(target) Release/obj.target/gcstats/src/gcstats.o
../src/gcstats.cc../src/gcstats.cc:132::19: 132:19: warning: warning: 'Call' is 'Call'deprecated  is[-Wdeprecated-declarations] deprecated
 [-Wdeprecated-declarations]
        afterGCCallback->Call(1, arguments);        afterGCCallback->Call(1, arguments);

                         ^                         ^

../../nan/nan.h:1646:3: note: 'Call' ../../nan/nan.hhas: 1646been: 3explicitly:  marked deprecatednote : here'Call'
 has been explicitly marked deprecated here  NAN_DEPRECATED inline v8::Local<v8::Value>

  ^
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:102../../nan/nan.h::40102:: 40: note: noteexpanded:  fromexpanded  macrofrom  'NAN_DEPRECATED'macro
'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
                                       ^
1 warning generated.
1 warning generated.
rm: ./Release/.deps/Release/obj.target/gcstats/src/gcstats.o.d.raw: No such file or directory
make: *** [Release/obj.target/gcstats/src/gcstats.o] Error 1
gyp  SOLINK_MODULE(target) Release/gcstats.node
 ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:239:12)
gyp ERR! System Darwin 17.4.0
gyp ERR! command "/usr/local/Cellar/node/10.9.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/me/Workspace/infrastructure/baas-client/node_modules/gc-stats/build/gcstats/v1.0.2/Release/node-v64-darwin-x64/gcstats.node" "--module_name=gcstats" "--module_path=/Users/me/Workspace/infrastructure/baas-client/node_modules/gc-stats/build/gcstats/v1.0.2/Release/node-v64-darwin-x64"
gyp ERR! cwd /Users/me/Workspace/infrastructure/baas-client/node_modules/gc-stats
gyp ERR! node -v v10.9.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/10.9.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/me/Workspace/infrastructure/baas-client/node_modules/gc-stats/build/gcstats/v1.0.2/Release/node-v64-darwin-x64/gcstats.node --module_name=gcstats --module_path=/Users/me/Workspace/infrastructure/baas-client/node_modules/gc-stats/build/gcstats/v1.0.2/Release/node-v64-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/me/Workspace/infrastructure/baas-client/node_modules/gc-stats/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:250:5)
node-pre-gyp ERR! System Darwin 17.4.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/10.9.0/bin/node" "/Users/me/Workspace/infrastructure/baas-client/node_modules/gc-stats/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/me/Workspace/infrastructure/baas-client/node_modules/gc-stats
node-pre-gyp ERR! node -v v10.9.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/Cellar/node/10.9.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/me/Workspace/infrastructure/baas-client/node_modules/gc-stats/build/gcstats/v1.0.2/Release/node-v64-darwin-x64/gcstats.node --module_name=gcstats --module_path=/Users/me/Workspace/infrastructure/baas-client/node_modules/gc-stats/build/gcstats/v1.0.2/Release/node-v64-darwin-x64' (1)
  COPY /Users/me/Workspace/infrastructure/baas-client/node_modules/gc-stats/build/gcstats/v1.0.2/Release/node-v64-darwin-x64/gcstats.node
  TOUCH Release/obj.target/action_after_build.stamptats@1.0.2~install: Failed to exec install script
npm WARN enoent ENOENT: no such file or directory, open '/Users/me/Workspace/infrastructure/baas-client/package.json'
npm WARN baas-client No description
npm WARN baas-client No repository field.
npm WARN baas-client No README data
npm WARN baas-client No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gc-stats@1.0.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gc-stats@1.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/me/.npm/_logs/2018-09-04T15_02_02_748Z-debug.log
```
